#!/bin/bash

# Works with multiple Files
# Needs the videofolder-path as argument
# Unique Name generator needs to be fixed

# Generates a "unique" name

namegen () {

date +"%d_%m_%Y_%N"

}


for f in $1/*\ *; do mv "$f" "${f// /_}"; done


for f in $1*
do
	echo "`basename $f | rev | cut -d. -f1 | rev`"
	echo " mv `basename $f` to $(namegen)"."`basename $f | rev | cut -d. -f1 | rev`?"
	read

done

